### ISSUE TITLE
im cannot go to virtual systems n dahliaos web version

### ISSUE THREAD

**Issue by ghost** [dahliaOS/graft#2]
**Describe the bug**

**What kind of a bug is it?**
Describe what kind of a bug it is. [e.g. Typo, visual, application bug]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. dahliaOS Linux, dahliaOS Zircon]
 - Device: [e.g. MacbookPro9,1, QEMU]

**dahliaOS build version**
Write what version of dahliaOS you were using.

**Additional context**

**Comment by bleonard252** [comment]
This isn't a vaild request at all, for multiple reasons.
1. You didn't even bother completing the form.
2. Graft cannot and will not work in the browser.
